services:
  db:
    image: postgres:15
    container_name: hillel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Hillel_Course_DB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hillel_app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/Hillel_Course_DB
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "database.py"]
    volumes:
      - .:/app

  tests:
    build: .
    container_name: hillel_tests
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/Hillel_Course_DB
    depends_on:
      app:
        condition: service_completed_successfully
    # Тільки запускаємо тести і зберігаємо результати
    command: ["pytest", "-v", "--alluredir=/app/allure-results"]
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure_server
    depends_on:
      - tests
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1

volumes:
  db_data:
